### ISSUE TITLE
Can't access SBCSAE wav file

### ISSUE THREAD

**Issue by DanielLin94144** [Nathan-Roll1/PSST#1]
Hi, Thanks for the great work! I found out that in the corpus website (https://www.linguistics.ucsb.edu/research/santa-barbara-corpus) only the transcripts can be accessed, whereas all the wav file links are broken. Can you share the data for reproducing your results? Thank you very much in advance!

**Comment by Nathan-Roll1** [comment]
Hi Daniel,

Of course! You can find the dataset here: https://huggingface.co/datasets/NathanRoll/SBC_segmented.
