### ISSUE TITLE
Error while running the colab notebook 

### ISSUE THREAD

**Issue by staru09** [Nathan-Roll1/PSST#2]
ImportError: cannot import name 'is_torch_less_than_1_11' from 'transformers.pytorch_utils' (/usr/local/lib/python3.10/dist-packages/transformers/pytorch_utils.py)

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
RuntimeError: Failed to import optimum.exporters.onnx.__main__ because of the following error (look up to see its traceback):
cannot import name 'is_torch_less_than_1_11' from 'transformers.pytorch_utils' (/usr/local/lib/python3.10/dist-packages/transformers/pytorch_utils.py)

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
   1390             return importlib.import_module("." + module_name, self.__name__)
   1391         except Exception as e:
-> 1392             raise RuntimeError(
   1393                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
   1394                 f" traceback):\n{e}"

**Comment by Nathan-Roll1** [comment]
Thanks for bringing this to my attention -- I've updated (1) the path to the non-quantizd tutorial, and (2) forced the installation of an older version of the transformers library in the quantized notebook. Let me know if you are still encountering any issues.

**Comment by staru09** [comment]
Thanks for fixing, It's working now.
Just a quick question are these (!!!!!) some sort of delimiters, I am kinda new to intonation.
Also any other resource to know about intonation units or detecting them in a sentence will be helpful.

**Comment by Nathan-Roll1** [comment]
Yes, the '!!!!!' token represents prosodic (~intonation unit/~intonational phrase) boundaries , which are somewhat akin to what you might think of as phrases. I would recommend following some of the references in our paper (i.e. Du Bois et al. 1992) for a much more comprehensive definition. We've also included a selection of past approaches to the same task as well. Good luck!

**Comment by staru09** [comment]
Thanks a lot

**Comment by staru09** [comment]
I read your paper and I had this doubt like while fine-tuning whisper on santa corpus, can it be used directly in mp3 format or do you people created spectogram for feeding.
